sudo: required
language: generic
services:
  - docker
before_script:
  - echo "start creating an image with dockerfile"
  - docker build -t chipmunkdev/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true chipmunkdev/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test success Travis CI"