sudo: required

language: generic

services:
  - docker
  -
before_script:
  - echo "start creating an image with dockerfile"
  - docker build -t chipmunkdev/docker-react-app -f Dockerfile.dev .
  -
script:
  - docker run -e CI=true chipmunkdev/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-492504490769"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
